#!/bin/bash
set -euo pipefail

# Creates a release build for the specified distro, and shoves it into a docker container. The dfiler executable will be
# on the PATH, so you can run it from within the container with `dfiler [OPTIONS]`
#
# Usage:
#   * script/docker-test <distro> [SOURCE=$(pwd)/fixture/source]
#
# This container will be build and run interatively. It'll have $2 volume mounted to ~/dotfiles as read only. The
# typical test case is to run `script/docker-test <os>` and from within the container run `dfiler -s dotfiles`.
#
# Available distros:
#   * stretch - Runs stretch slim
#   * jessie - Runs jessie slim

main() {
  local dfiler_dir="${2:-$(pwd)/fixture/source}"
  echo "Mounting ${dfiler_dir}"

  docker build -f docker/Dockerfile.$1 -t dfiler/$1 .
  docker run --rm -it -v "${dfiler_dir}:/home/tester/dotfiles:ro" dfiler/$1
}

main "$@"
